////////////////////////////////////////
//   最近实装单位：newThings 新职业1 新武器2 新幻想e3 新幻想b4 新敌人5
//   情报：willThings   标题(words)     图     url链接(urlOut)    文字（justword）
//   当前活动：nowActivity 卡池1 活动主题图2
var G_value = [
    { kind:'newThings', kindSecond:'2', picId:'230002', isShow:'1', urlOut:'', words:'', EBWname:'夜払いの氷剣', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'230003', isShow:'1', urlOut:'', words:'', EBWname:'朝日差す氷斧', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'230004', isShow:'1', urlOut:'', words:'', EBWname:'氷原弓', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'230005', isShow:'1', urlOut:'', words:'', EBWname:'破砦垂氷', justWord:''},
    { kind:'newThings', kindSecond:'2', picId:'230006', isShow:'1', urlOut:'', words:'', EBWname:'砕氷の槌', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'230007', isShow:'1', urlOut:'', words:'', EBWname:'荒れ狂う剛禍の巨魁', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'230008', isShow:'1', urlOut:'', words:'', EBWname:'砂漠のシャドウバイパー', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'230009', isShow:'1', urlOut:'', words:'', EBWname:'*視線も集めております', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'230010', isShow:'1', urlOut:'', words:'', EBWname:'守護の要ゾルキシア兵長', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'230011', isShow:'1', urlOut:'', words:'', EBWname:'*エーリンゼ様のバカンス', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'230012', isShow:'1', urlOut:'', words:'', EBWname:'天の弾丸ゾルキシア狙撃兵', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'230013', isShow:'1', urlOut:'', words:'', EBWname:'*花火を楽しむなら夜なのじゃ', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'230014', isShow:'1', urlOut:'', words:'', EBWname:'*貝殻ゴブリンがやってきた', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'230015', isShow:'1', urlOut:'', words:'', EBWname:'御柱の守護者バラージアーム', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'230016', isShow:'1', urlOut:'', words:'', EBWname:'御柱のクロノゲート', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'230017', isShow:'1', urlOut:'', words:'', EBWname:'*クラスパートナーのバカンス', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'230018', isShow:'1', urlOut:'', words:'', EBWname:'巡視するレーザーゲイザー', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'230019', isShow:'1', urlOut:'', words:'', EBWname:'新米亭主のお手伝い', justWord:''},
    { kind:'newThings', kindSecond:'3', picId:'230020', isShow:'1', urlOut:'', words:'', EBWname:'*アステルリーズ・ビーチの夏', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'230021', isShow:'1', urlOut:'', words:'', EBWname:'遺留のオートマトン', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'230022', isShow:'1', urlOut:'', words:'', EBWname:'朱に染まりし機神', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'230023', isShow:'1', urlOut:'', words:'', EBWname:'摂理の破戒者', justWord:''},
    { kind:'willThings', kindSecond:'1', picId:'230024', isShow:'1', urlOut:'https://www.bilibili.com/video/BV1Rj411m7ga', words:'即将实装 / 新职业 / 枪兵', EBWname:'', justWord:''},
    { kind:'nowActivity', kindSecond:'1', picId:'230025', isShow:'1', urlOut:'', words:'', EBWname:'', justWord:''},
    { kind:'nowActivity', kindSecond:'1', picId:'230026', isShow:'1', urlOut:'', words:'', EBWname:'', justWord:''},
    { kind:'nowActivity', kindSecond:'2', picId:'230001', isShow:'1', urlOut:'', words:'マンスリーイベント「トロピカルリゾート」を開催中！', EBWname:'', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'230027', isShow:'1', urlOut:'', words:'', EBWname:'*貝を集めし邪教徒', justWord:''},
    { kind:'newThings', kindSecond:'4', picId:'230028', isShow:'1', urlOut:'', words:'', EBWname:'*貝殻ゴブリン', justWord:''},
    { kind:'willThings', kindSecond:'1', picId:'230029', isShow:'1', urlOut:'https://www.bilibili.com/video/BV1E14y1o7cf', words:'通信九 / 熟肉总结 / 蓝色协议中文站', EBWname:'', justWord:''},
    { kind:'willThings', kindSecond:'1', picId:'230030', isShow:'1', urlOut:'https://www.bilibili.com/video/BV1DM4y1p7Lb', words:'pv预告 / 欧美服开启预告', EBWname:'', justWord:''},
]